# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75ffb5818e0d3d65b06fc5ec7911ee44e7478c64aa3eea58b0171f60824b4d7b69d1b34294deffadab3030dbda50aef5140efac37a7c9acefeea153b7596f084

test:
  secret_key_base: 6e57a409983050685d143cff14060a840769d790ce5ec91bcdc49d0d381fce1839681ea01fcb233d3f496463c8c255ecf4889893f54df3ff77c85030e3f4df37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
